=== UDDI/juddi/juddi-client/src/main/resources/xsd/uddi-client.xsd
<xsd:schema elementFormDefault='qualified'
  targetNamespace='urn:juddi-apache-org:v3_client' version='1.0'
            xmlns:tns='urn:juddi-apache-org:v3_client'
  xmlns:ns1='http://www.w3.org/2000/09/xmldsig#' xmlns:xsd='http://www.w3.org/2001/XMLSchema'>
  <xsd:element name="uddi">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element type="xsd:short" name="reloadDelay" />
        <xsd:element name="client" nillable="false">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="nodes">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="node" maxOccurs="unbounded"
													minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element type="xsd:string" name="name" />
                          <xsd:element type="xsd:string" name="description" />
                       
                          <xsd:element name="properties" minOccurs="0">
                            <xsd:complexType>
                              <xsd:sequence>
                                <xsd:element name="property" maxOccurs="unbounded"
																			minOccurs="0">
                                  <xsd:complexType>
                                    <xsd:simpleContent>
                                      <xsd:extension base="xsd:string">
                                        <xsd:attribute type="xsd:string"
																							name="name" use="optional" />
                                        <xsd:attribute type="xsd:string"
																							name="value" use="optional" />
                                      </xsd:extension>
                                    </xsd:simpleContent>
                                  </xsd:complexType>
                                </xsd:element>
                              </xsd:sequence>
                            </xsd:complexType>
                          </xsd:element>
                          <xsd:element type="xsd:string" name="proxyTransport" />
                          <xsd:element type="xsd:anyURI" name="custodyTransferUrl" />
                          <xsd:element type="xsd:anyURI" name="inquiryUrl" />
                          <xsd:element type="xsd:anyURI" name="publishUrl" />
                          <xsd:element type="xsd:anyURI" name="securityUrl" />
                          <xsd:element type="xsd:anyURI" name="subscriptionUrl" />
                          <xsd:element type="xsd:anyURI" name="subscriptionListenerUrl" />
                          <xsd:element type="xsd:anyURI" name="juddiApiUrl"  nillable="true"/>
                          <xsd:element type="xsd:string" name="factoryInitial"  nillable="true"/>
                          <xsd:element type="xsd:string" name="factoryURLPkgs"  nillable="true"/>
                          <xsd:element type="xsd:string" name="factoryNamingProvider"  nillable="true"/>

                        </xsd:sequence>
                        <xsd:attribute type="xsd:boolean" name="isHomeJUDDI"
															use="optional" />
                      </xsd:complexType>
                    </xsd:element>
                
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
              <xsd:element name="clerks">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="clerk" maxOccurs="unbounded"
                          minOccurs="0">
                      <xsd:complexType>
                        <xsd:sequence>
                          <xsd:element name="wsdl"  type="tns:wsdl" maxOccurs="unbounded" minOccurs="0" nillable="true"></xsd:element>
                          <xsd:element name="class" type="xsd:string" maxOccurs="unbounded" minOccurs="0" nillable="true"> </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute type="xsd:string" name="name"
                              use="required" />
                        <xsd:attribute type="xsd:string" name="node"
                              use="required" />
                        <xsd:attribute type="xsd:string" name="publisher"
                              use="required" />
                        <xsd:attribute type="xsd:string" name="password"
                              use="required" />
                        <xsd:attribute type="xsd:boolean" name="isPasswordEncrypted"
                              use="optional" default="false"  />
                        <xsd:attribute type="xsd:string" name="cryptoProvider"
                             use="optional"  />
                        
                        <xsd:attribute type="xsd:string" name="businessKey"
                              use="optional" />
                        <xsd:attribute type="xsd:string" name="businessName"
                              use="optional" />
                        <xsd:attribute type="xsd:string" name="keyDomain"
                              use="optional" />
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="xregister">
                      <xsd:complexType>
                        <xsd:sequence >

                          <xsd:element name="servicebinding" maxOccurs="unbounded" nillable="true">
                            <xsd:complexType>
                              <xsd:simpleContent>
                                <xsd:extension base="xsd:string">
                                  <xsd:attribute type="xsd:string" name="bindingKey"/>
                                  <xsd:attribute type="xsd:string" name="fromClerk"/>
                                  <xsd:attribute type="xsd:string" name="toClerk"/>
                                </xsd:extension>
                              </xsd:simpleContent>
                            </xsd:complexType>
                          </xsd:element>

                          <xsd:element name="business" maxOccurs="unbounded" nillable="true">
                            <xsd:complexType>
                              <xsd:simpleContent>
                                <xsd:extension base="xsd:string">
                                  <xsd:attribute type="xsd:string" name="bindingKey"/>
                                  <xsd:attribute type="xsd:string" name="fromClerk"/>
                                  <xsd:attribute type="xsd:string" name="toClerk"/>
                                </xsd:extension>
                              </xsd:simpleContent>
                            </xsd:complexType>
                          </xsd:element>


                        </xsd:sequence>

                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute type="xsd:boolean" name="registerOnStartup"
                        use="optional" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute type="xsd:string" name="name" />
          </xsd:complexType>
        </xsd:element>

       
      </xsd:sequence>
     
    </xsd:complexType>
  </xsd:element>


  <xsd:complexType name="wsdl"  >
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute type="xsd:string" name="businessKey"
                use="optional"/>
        <xsd:attribute type="xsd:string" name="businessName"
              use="optional" />
        <xsd:attribute type="xsd:string" name="keyDomain"
              use="optional" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

</xsd:schema>

=== UDDI/juddi/juddi-client/src/test/resources/META-INF/uddi2.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<uddi xmlns="urn:juddi-apache-org:v3_client" xsi:schemaLocation="classpath:/xsd/uddi-client.xsd">
    <reloadDelay>5000</reloadDelay>
    <client name="second-client">
		<nodes>
			<node isHomeJUDDI="true">
				<name>default</name> 
				<description>Local jUDDI node</description>
				<properties>
					<property name="serverName" value="localhost" />
					<property name="serverPort" value="8880" />
				</properties>
				<!-- JAX-WS Transport -->
				<proxyTransport>org.apache.juddi.v3.client.transport.JAXWSTransport</proxyTransport>
				<custodyTransferUrl>http://${serverName}:${serverPort}/juddiv3/services/custody-transfer?wsdl</custodyTransferUrl>
				<inquiryUrl>http://${serverName}:${serverPort}/juddiv3/services/inquiry?wsdl</inquiryUrl>
		        <publishUrl>http://${serverName}:${serverPort}/juddiv3/services/publish?wsdl</publishUrl>
		        <securityUrl>http://${serverName}:${serverPort}/juddiv3/services/security?wsdl</securityUrl>
				<subscriptionUrl>http://${serverName}:${serverPort}/juddiv3/services/subscription?wsdl</subscriptionUrl>
				<subscriptionListenerUrl>http://${serverName}:${serverPort}/juddiv3/services/subscription-listener?wsdl</subscriptionListenerUrl>
				<juddiApiUrl>http://${serverName}:${serverPort}/juddiv3/services/juddi-api?wsdl</juddiApiUrl>
			</node>
			<node>
				<name>med</name>
				<description>jUDDI node in other Department</description>
				<proxyTransport>org.apache.juddi.v3.client.transport.JAXWSTransport</proxyTransport>
				<custodyTransferUrl>http://med:8080/juddiv3/services/custody-transfer?wsdl</custodyTransferUrl>
				<inquiryUrl>http://med:8080/juddiv3/services/inquiry?wsdl</inquiryUrl>
		        <publishUrl>http://med:8080/juddiv3/services/publish?wsdl</publishUrl>
		        <securityUrl>http://med:8080/juddiv3/services/security?wsdl</securityUrl>
				<subscriptionUrl>http://med:8080/juddiv3/services/subscription?wsdl</subscriptionUrl>
				<subscriptionListenerUrl>http://med:8080/juddiv3/services/subscription-listener?wsdl</subscriptionListenerUrl>
				<juddiApiUrl>http://med:8080/juddiv3/services/juddi-api?wsdl</juddiApiUrl>
			</node>
		</nodes>
		
		<clerks registerOnStartup="false">
		   <clerk name="default" node="default" publisher="root" password="root"/>
	       <clerk name="medroot" node="med"     publisher="root" password="root"/> 
	       <xregister>
		       <service bindingKey="uddi:juddi.apache.org:servicebindings-subscriptionlistener-ws" fromClerk="default" toClerk="medroot"/>
		   </xregister>
	   </clerks>
	  
	</client>
</uddi>

=== UDDI/juddi/uddi-tck/src/main/resources/META-INF/uddi.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<uddi xmlns="urn:juddi-apache-org:v3_client" xsi:schemaLocation="classpath:/xsd/uddi-client.xsd">
    <reloadDelay>5000</reloadDelay>
    <client name="test-client">
		<nodes>
			<node isHomeJUDDI="true">
			    <!-- required 'default' node -->
				<name>default</name> 
				<description>Main jUDDI node</description>
				<properties>
					<property name="serverName" value="localhost" />
					<property name="serverPort" value="8880" />
				</properties>
				<!-- systinet
            <proxyTransport>org.apache.juddi.v3.client.transport.JAXWSTransport</proxyTransport>
            <inquiryUrl>http://${serverName}:${serverPort}/registry/uddi/inquiry</inquiryUrl>
            <publishUrl>http://${serverName}:${serverPort}/registry/uddi/publishing</publishUrl>
            <securityUrl>http://${serverName}:${serverPort}/registry/uddi/security</securityUrl>
				-->
				<!-- JAX-WS Transport -->
				<proxyTransport>org.apache.juddi.v3.client.transport.JAXWSTransport</proxyTransport>
				<custodyTransferUrl>http://${serverName}:${serverPort}/juddiv3/services/custody-transfer</custodyTransferUrl>
				<inquiryUrl>http://${serverName}:${serverPort}/juddiv3/services/inquiry</inquiryUrl>
		        <publishUrl>http://${serverName}:${serverPort}/juddiv3/services/publish</publishUrl>
		        <securityUrl>http://${serverName}:${serverPort}/juddiv3/services/security</securityUrl>
				<subscriptionUrl>http://${serverName}:${serverPort}/juddiv3/services/subscription</subscriptionUrl>
				<subscriptionListenerUrl>http://${serverName}:${serverPort}/juddiv3/services/subscription-listener</subscriptionListenerUrl>
				<juddiApiUrl>http://${serverName}:${serverPort}/juddiv3/services/juddi-api</juddiApiUrl>
				 
				<!-- In VM Transport Settings 
				<proxyTransport>org.apache.juddi.v3.client.transport.InVMTransport</proxyTransport>
				<custodyTransferUrl>org.apache.juddi.api.impl.UDDICustodyTransferImpl</custodyTransferUrl>
				<inquiryUrl>org.apache.juddi.api.impl.UDDIInquiryImpl</inquiryUrl>
		        <publishUrl>org.apache.juddi.api.impl.UDDIPublicationImpl</publishUrl>
		        <securityUrl>org.apache.juddi.api.impl.UDDISecurityImpl</securityUrl>
				<subscriptionUrl>org.apache.juddi.api.impl.UDDISubscriptionImpl</subscriptionUrl>
				<subscriptionListenerUrl>org.apache.juddi.api.impl.UDDISubscriptionListenerImpl</subscriptionListenerUrl>
				<juddiApiUrl>org.apache.juddi.api.impl.JUDDIApiImpl</juddiApiUrl>
				-->
				<!-- RMI Transport Settings 
				<proxyTransport>org.apache.juddi.v3.client.transport.RMITransport</proxyTransport>
				<custodyTransferUrl>/juddiv3/UDDICustodyTransferService</custodyTransferUrl>
				<inquiryUrl>/juddiv3/UDDIInquiryService</inquiryUrl>
		        <publishUrl>/juddiv3/UDDIPublicationService</publishUrl>
		        <securityUrl>/juddiv3/UDDISecurityService</securityUrl>
				<subscriptionUrl>/juddiv3/UDDISubscriptionService</subscriptionUrl>
				<subscriptionListenerUrl>/juddiv3/UDDISubscriptionListenerService</subscriptionListenerUrl>
				<juddiApiUrl>/juddiv3/JUDDIApiService</juddiApiUrl>
				<javaNamingFactoryInitial>org.jnp.interfaces.NamingContextFactory</javaNamingFactoryInitial>
				<javaNamingFactoryUrlPkgs>org.jboss.naming</javaNamingFactoryUrlPkgs>
				<javaNamingProviderUrl>jnp://localhost:1099</javaNamingProviderUrl>
				-->
			</node>
			<node>
				<name>med</name>
				<description>jUDDI node in other Department</description>
				<proxyTransport>org.apache.juddi.v3.client.transport.JAXWSTransport</proxyTransport>
				<custodyTransferUrl>http://med:8080/juddiv3/services/custody-transfer/</custodyTransferUrl>
				<inquiryUrl>http://med:8080/juddiv3/services/inquiry/</inquiryUrl>
		        <publishUrl>http://med:8080/juddiv3/services/publish/</publishUrl>
		        <securityUrl>http://med:8080/juddiv3/services/security/</securityUrl>
				<subscriptionUrl>http://med:8080/juddiv3/services/subscription/</subscriptionUrl>
				<subscriptionListenerUrl>http://med:8080/juddiv3/services/subscription-listener/</subscriptionListenerUrl>
				<juddiApiUrl>http://med:8080/juddiv3/services/juddi-api?wsdl</juddiApiUrl>
			</node>
		</nodes>
		
		<clerks registerOnStartup="false">
		   <clerk name="default" node="default" publisher="root" password="root"  />
	       <clerk name="medroot" node="med"     publisher="root" password="root"/>
	       <xregister>
		       <service bindingKey="uddi:juddi.apache.org:servicebindings-subscriptionlistener-ws" fromClerk="default" toClerk="medroot"/>
		   </xregister>
		   <subscription subscriptionKey="   " clerk="medroot" />
	   </clerks>
	  
	</client>
</uddi>

=== UDDI/juddi/juddi-client.net/juddi-client.net-sample/uddi.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<uddi xmlns="urn:juddi-apache-org:v3_client" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="C:\juddi\trunkcur\juddi-client\src\main\resources\xsd\uddi-client.xsd">
    <reloadDelay>5000</reloadDelay>
    <client name="test-client">
		<nodes>
			<node isHomeJUDDI="true"> 
			    <!-- required 'default' node -->
				<name>default</name> 
				<description>Main jUDDI node</description>
				<properties>
					<property name="serverName" value="uddi-jbossoverlord.rhcloud.com" />
					<property name="serverPort" value="80" />
				</properties>
				<!-- JAX-WS Transport -->
				<proxyTransport>org.apache.juddi.v3.client.transport.AspNetTransport</proxyTransport>
				<custodyTransferUrl>http://${serverName}:${serverPort}/services/custody-transfer?wsdl</custodyTransferUrl>
				<inquiryUrl>http://${serverName}:${serverPort}/services/inquiry?wsdl</inquiryUrl>
		        <publishUrl>http://${serverName}:${serverPort}/services/publish?wsdl</publishUrl>
		        <securityUrl>http://${serverName}:${serverPort}/services/security?wsdl</securityUrl>
				<subscriptionUrl>http://${serverName}:${serverPort}/services/subscription?wsdl</subscriptionUrl>
				<subscriptionListenerUrl>http://${serverName}:${serverPort}/services/subscription-listener?wsdl</subscriptionListenerUrl>
				<juddiApiUrl>http://${serverName}:${serverPort}/services/juddi-api?wsdl</juddiApiUrl>
				<!-- In VM Transport Settings 
				<proxyTransport>org.apache.juddi.v3.client.transport.InVMTransport</proxyTransport>
				<custodyTransferUrl>org.apache.juddi.api.impl.UDDICustodyTransferImpl</custodyTransferUrl>
				<inquiryUrl>org.apache.juddi.api.impl.UDDIInquiryImpl</inquiryUrl>
		        <publishUrl>org.apache.juddi.api.impl.UDDIPublicationImpl</publishUrl>
		        <securityUrl>org.apache.juddi.api.impl.UDDISecurityImpl</securityUrl>
				<subscriptionUrl>org.apache.juddi.api.impl.UDDISubscriptionImpl</subscriptionUrl>
				<subscriptionListenerUrl>org.apache.juddi.api.impl.UDDISubscriptionListenerImpl</subscriptionListenerUrl>
				<juddiApiUrl>org.apache.juddi.api.impl.JUDDIApiImpl</juddiApiUrl>
				-->
				<!-- RMI Transport Settings 
				<proxyTransport>org.apache.juddi.v3.client.transport.RMITransport</proxyTransport>
				<custodyTransferUrl>/juddiv3/UDDICustodyTransferService</custodyTransferUrl>
				<inquiryUrl>/juddiv3/UDDIInquiryService</inquiryUrl>
		        <publishUrl>/juddiv3/UDDIPublicationService</publishUrl>
		        <securityUrl>/juddiv3/UDDISecurityService</securityUrl>
				<subscriptionUrl>/juddiv3/UDDISubscriptionService</subscriptionUrl>
				<subscriptionListenerUrl>/juddiv3/UDDISubscriptionListenerService</subscriptionListenerUrl>
				<juddiApiUrl>/juddiv3/JUDDIApiService</juddiApiUrl>
				<javaNamingFactoryInitial>org.jnp.interfaces.NamingContextFactory</javaNamingFactoryInitial>
				<javaNamingFactoryUrlPkgs>org.jboss.naming</javaNamingFactoryUrlPkgs>
				<javaNamingProviderUrl>jnp://localhost:1099</javaNamingProviderUrl>
				-->
			</node>
			<node>
				<name>med</name>
				<description>jUDDI node in other Department</description>
				<proxyTransport>org.apache.juddi.v3.client.transport.JAXWSTransport</proxyTransport>
				<custodyTransferUrl>http://med:8080/juddiv3/services/custody-transfer?wsdl</custodyTransferUrl>
				<inquiryUrl>http://med:8080/juddiv3/services/inquiry?wsdl</inquiryUrl>
		        <publishUrl>http://med:8080/juddiv3/services/publish?wsdl</publishUrl>
		        <securityUrl>http://med:8080/juddiv3/services/security?wsdl</securityUrl>
				<subscriptionUrl>http://med:8080/juddiv3/services/subscription?wsdl</subscriptionUrl>
				<subscriptionListenerUrl>http://med:8080/juddiv3/services/subscription-listener?wsdl</subscriptionListenerUrl>
				<juddiApiUrl>http://med:8080/juddiv3/services/juddi-api?wsdl</juddiApiUrl>
			</node>
		</nodes> 
		 
		<clerks registerOnStartup="false">
		   <clerk name="default" node="default" publisher="root" password="root"/>
	       <clerk name="medroot" node="med"     publisher="root" password="root"/> 
	       <xregister>
		       <servicebinding bindingKey="uddi:juddi.apache.org:servicebindings-subscriptionlistener-ws" fromClerk="default" toClerk="medroot"/>
		   </xregister>
	   </clerks>
	  
	</client>
</uddi>

=== UDDI/juddi/juddi-console/uddi-portlets/src/main/resources/META-INF/uddi.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!--
 * Copyright 2001-2009 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */ -->

<uddi xmlns="urn:juddi-apache-org:v3_client" xsi:schemaLocation="classpath:/xsd/uddi-client.xsd">
    <reloadDelay>5000</reloadDelay>
    <client name="uddi-portlet-client">
		<nodes>
			<node isHomeJUDDI="true">
				<name>default</name>
				<properties>
					<property name="serverName" value="localhost"/>
					<property name="serverPort" value="8080"/>
					<property name="rmiPort" value="1099"/>
					<!-- for UDDI nodes that use HTTP u/p, using the following 
					<property name="basicAuthUsername" value="root" />
					<property name="basicAuthPassword" value="password" />
					<property name="basicAuthPasswordIsEncrypted" value="false" />
					<property name="basicAuthPasswordCryptoProvider" value="org.apache.juddi.v3.client.crypto.AES128Cryptor (an example)" />-->
				</properties>
				<description>Main jUDDI node</description>
				<!-- JAX-WS Transport -->
				<proxyTransport>org.apache.juddi.v3.client.transport.JAXWSTransport</proxyTransport>
				<custodyTransferUrl>http://${serverName}:${serverPort}/juddiv3/services/custody-transfer</custodyTransferUrl>
				<inquiryUrl>http://${serverName}:${serverPort}/juddiv3/services/inquiry</inquiryUrl>
		        <publishUrl>http://${serverName}:${serverPort}/juddiv3/services/publish</publishUrl>
		        <securityUrl>http://${serverName}:${serverPort}/juddiv3/services/security</securityUrl>
				<subscriptionUrl>http://${serverName}:${serverPort}/juddiv3/services/subscription</subscriptionUrl>
				<subscriptionListenerUrl>http://${serverName}:${serverPort}/juddiv3/services/subscription-listener</subscriptionListenerUrl>
				<juddiApiUrl>http://${serverName}:${serverPort}/juddiv3/services/juddi-api</juddiApiUrl>
				<!-- In VM Transport Settings 
				<proxyTransport>org.apache.juddi.v3.client.transport.InVMTransport</proxyTransport>
				<custodyTransferUrl>org.apache.juddi.api.impl.UDDICustodyTransferImpl</custodyTransferUrl>
				<inquiryUrl>org.apache.juddi.api.impl.UDDIInquiryImpl</inquiryUrl>
		        <publishUrl>org.apache.juddi.api.impl.UDDIPublicationImpl</publishUrl>
		        <securityUrl>org.apache.juddi.api.impl.UDDISecurityImpl</securityUrl>
				<subscriptionUrl>org.apache.juddi.api.impl.UDDISubscriptionImpl</subscriptionUrl>
				<subscriptionListenerUrl>org.apache.juddi.api.impl.UDDISubscriptionListenerImpl</subscriptionListenerUrl>
				<juddiApiUrl>org.apache.juddi.api.impl.JUDDIApiImpl</juddiApiUrl>
				-->
				<!-- RMI Transport Settings 
				<proxyTransport>org.apache.juddi.v3.client.transport.RMITransport</proxyTransport>
				<custodyTransferUrl>/juddiv3/UDDICustodyTransferService</custodyTransferUrl>
				<inquiryUrl>/juddiv3/UDDIInquiryService</inquiryUrl>
		        <publishUrl>/juddiv3/UDDIPublicationService</publishUrl>
		        <securityUrl>/juddiv3/UDDISecurityService</securityUrl>
				<subscriptionUrl>/juddiv3/UDDISubscriptionService</subscriptionUrl>
				<subscriptionListenerUrl>/juddiv3/UDDISubscriptionListenerService</subscriptionListenerUrl>
				<juddiApiUrl>/juddiv3/JUDDIApiService</juddiApiUrl>
				<javaNamingFactoryInitial>org.jnp.interfaces.NamingContextFactory</javaNamingFactoryInitial>
				<javaNamingFactoryUrlPkgs>org.jboss.naming</javaNamingFactoryUrlPkgs>
				<javaNamingProviderUrl>jnp://${serverName}:${rmiPort}</javaNamingProviderUrl>
				-->
			</node>
		</nodes>
		<clerks registerOnStartup="false">
		   <clerk name="MarketingCratchit" node="default" publisher="marketing" password="marketing" isPasswordEncrypted="false" cryptoProvider=""/> 
	   </clerks>
	</client> 
   
</uddi>
